### ISSUE TITLE
[WIP] - Concept - airdrop snapshot data generator

### ISSUE THREAD

**Issue by lumtis** [ignite/cli-plugin-airdrop#1]
# Airdrop snapshot data generator

<img src="https://user-images.githubusercontent.com/7040350/196845482-a3a3bffa-338a-4bff-b894-7aef3d241279.png" alt="drawing" width="200"/>

The airdrop snapshot generator is a new command or set of commands allowing to create snapshot for airdrop with mainnet.
Chains distribute airdrop in the following way:
- Allocating the tokens directly in the account balance, or a small amount named dust wallet
- Use a `claim` module that define rules for airdrop distribution and airdrop allocations (claim record)

We are developing a general usage `claim` module, so we can use this module as a reference for this functionality.
Claim module contains claim record in its genesis state for eligible addresses: https://github.com/ignite/modules/blob/main/x/claim/spec/01_state.md

Ignite airdrop snapshot generator is a command that allows generating a genesis state with dust wallet and claim records filled depending on the rules for the airdrop.
The rules would be stored in a yml file: `airdrop.yml`

### `ignite airdrop generate [airdrop_config] [input_genesis] > [output_genesis]`

The command parses the `airdrop_config` adds the dust wallet, and the claim records in the input genesis, create the output genesis

## Airdrop config

Designing and specifying the config file is the first step in this task. It should include all flexibility related to airdrop:
- Snapshot for staking, liquidity, etc...
- Date
- Mathematical formula for the amount
- Excluded addresses

Example format
```yml
version: 0.1.0

airdrop_token: ufoo

# balance as dust wallet for each eligible account to be able to perform first action
dust_wallet: 1

# list of snapshots
snapshots:
- ....
```

Snapshot:
```yml
# Type of snapshot
types: [staking|liquidity]

# Snapshot chain
chain: cosmos-hub

# Denom, related coin denom to stake for example, or pair for liquidity pool
denom: uatom

date: 2022-01-01T00:00:00Z

# TBD
formula:
  type: quadratic
  value: 2
  ...

# list of excluded addresses
excluded:
- ...
# TODO: rule for exclusion like exclusion after a specific balance
```

## Phases

The process of generating a genesis state from snapshots should be divided into different phases with the ability to save file between phases.
The reason is that if a user want to add an excluded address or change the airdrop formula, they should fetch the chain data again.
The phases:
- Parsing chain from data -> raw snapshot data
- Applying formula and excluded-addresses -> processed snapshot data
- Gathering snapshots -> genesis state

We can provide a full command that runs all phases and save intermediary files
```
ignite airdrop generate [airdrop_config] [input_genesis] > [output_genesis]
```
And command for each phase:
```
ignite airdrop raw airdrop.yml > raw.csv
ignite airdrop process airdrop.yml raw.csv > processed.csv
ignite airdrop genesis airdrop.yml processed.csv genesis.json > genesis.json
```
